### ISSUE TITLE
PEMapModder's ghost is talking to you

### ISSUE THREAD

**Issue by PEMapModders** [PEMapModders/repo#1]

**Comment by PEMapModders** [comment]
@Gamecrafter my name is not Chris! You really have to poke around GitHub less. It was just a dummy name I used when I had to make up a name. "Chris Wong" is the standard first-person dummy name in the English public exams in Hong Kong.

I rarely check this account. Only use this account for contacting me for something really important. (You can spread the word about this)

**Comment by PEMapModders** [comment]
@Gamecrafter You must have been referring to [this](https://github.com/Falkirks/TeamShog#team-members-in-order-of-joining) right? Didn't you see the quotes?

**Comment by PEMapModders** [comment]
As for face reveal:

![Steve](https://s-media-cache-ak0.pinimg.com/236x/4a/76/72/4a76729aad73157f7dedcda1e8ef53f9.jpg)

**Comment by ifvictr** [comment]
@PEMapModders I have to admit that I like poking users' old repositories. So your name isn't Chris, okay. I just put that out there, people had been messaging me about that, I just gagged them with "Chris". And yes, I did see the quotes, but I was just assuming that was your actual first name (because I didn't give it a second thought). And yes, the face reveal is satisfying. Now how many people know about this? I'm not the only one, am I?

**Comment by PEMapModders** [comment]
I guess you are the only one :P

Just that I rarely check this.

**Comment by ifvictr** [comment]
I don't think too many people should know about this, as this would bring you too much attention, therefore bringing the MCPE community to you.

**Comment by PEMapModders** [comment]
I realized that I forgot to clarify a few things:
- I am no longer worried about PocketMine's futurem not only because it is already unsalvageable and it is pointless to continue development of it, but also that PocketMine is not a commercial/whatever project like those third-party builds. PocketMine was originally for documenting the MCPE protocol. The documentary
  - @Gamecrafter please help me post this as a new reply at my Farewell thread.
- I mentioned that Nukkit is like a port of PocketMine and lacks originality, which led to misunderstanding. I was pointing out that I was no longer interested in PocketMine-related stuff anymore because of its nature. So I was considering about another server software. And since I was planning about something totally new, I think that the PocketMine's (and Bukkit's as well, for your information) structure is a bit out of fashion, so I was not interested in Nukkit either, since Nukkit's structure is similar to PocketMine to a large extent. This has totally nothing to do with being unhappy about Nukkit being "finished earlier than my own server software", because I don't have my own server software at all. On the other hand, being friendly/familiar to Bukkit and PocketMine developers did not appear to have much importance to me, because what I expected was a better API that can solve many loopholes in the Bukkit-/PocketMine-style API. As you know, I cherish the beauty of code more than how many people use it. Popular or not, this is just a short term problem in your life. It is really worthless (to me) that we keep creating the same thing again and again. If you are really so concerned about being Bukkit-friendly, you could just make a Bukkit plugin that lets MCPE players connect (yeah, why hadn't anyone thought of this at all if all they want is really a "fast" "functional" "persistent" server rather than popularity, fame, reputation, independence, permissions, fans, followers, and other yucky things? Is the community really so lack of creativity? Not targetting at anyone though; everyone has his own reasons). Of course there is the need of MCPE servers that are fast and useful, but that's not what I am interested in as an amateur programmer. (I never interfered and tried to stop other people from working on server software lacking originality; I at most pointed out that I don't like them) (Please, I am not like those politicians like Mu Zedong who wanted to get rid of particular political rivals and called upon a revolution in the whole country that destroyed most of the whole country's assets and society just to overthrow a few people who _potentially_ had more power than him)
  - @hoyinm14mc @MagicDroidX you might want to read this.
- I forgot to thank the community for many minor things:
  - -2 marks in my composition in an exam that was quite important two years ago
    - Probably it came to Google's attention, but a few months ago, typing `minecraft looking for sta` would result in the first prediction `minecraft looking for staffs`. The evil `staffs`.
  - -∞ time waiting for PhpStorm to stop hanging, for Chrome to load the forum page, for PHP to startup, rather than doing my homework
  - Poorer speaking skills. I used to speak shorter sentences. Now my teacher is saying that people cannot understand my sentences because my sentences are usually phrases connected by "that", "which is", "which makes", "particularly", "such as", "while", etc.
  - Better speaking skills. I don't think I was able to layout my points so clearly before.
  - @Gamecrafter please also post this for me.

Please keep a low profile on this comment and this issue and this repo and this account. I only wish to talk to those who are actually involved, not random passers-by who bump in without knowing the actual background details.
So if you want to quote anything from this message, you can refer to this issue as "words from a low-profile but genuine ghost of @PEMapModder".

Evidence that I am genuine? Who cares.

Will I login into this account again? Probably, maybe someday I would get bored again and check this issue again. Who knows? Maybe never.

**Comment by ifvictr** [comment]
@PEMapModders Do I post the one about Nukkit also? I've posted the other two.

**Comment by falkirks** [comment]
@PEMapModders We are having issues setting up the `pmt.mcpe.me` server.

**Comment by PEMapModders** [comment]
@Falkirks it seems that the nginx configuration you are using doesn't redirect `/**/` to `/**/index.php`?

**Comment by PEMapModders** [comment]
As for `pmb`, I have deleted most files from my computer, so I can't find a backup of the original source code there. However, you should be able to initialize a new watcher using [pmwatch](https://github.com/PEMapModder/pmwatch) (forgot to transfer that repo), start it through a screen, then write a simple script that reports the status using files generated in the pmwatch directory.

**Comment by falkirks** [comment]
@PEMapModders We were getting "RuntimeException: Directory name must not be empty.
at /var/www/html/functions.php:456"

**Comment by PEMapModders** [comment]
@Falkirks seems like you didn't add write access of `/var/www` to nginx.

Previously for Apache I did something like this:

``` bash
chown -R www-data:www-data /var/www
```

**Comment by ifvictr** [comment]
@PEMapModders There's this new user on the forums. Their username is called "SOFe", and they also have a GitHub account under the name of "SOF3". I kinda like her. And you probably would've too.

**Comment by PEMapModders** [comment]
@Gamecrafter Quite.

BTW https://gitter.im/PocketMine/PocketMine-MP?at=574207bc08a18f700b829e27 don't break your own promise.

**Comment by ifvictr** [comment]
@PEMapModders I said I would leave soon, but only if nothing changes. I've noticed a spark.

**Comment by PEMapModders** [comment]
@Gamecrafter what **_if_** I tell you that I know @SOF3 in real life?

**Comment by ifvictr** [comment]
@PEMapModders What about it, if you knew him/her/them in real life? I even had a theory once, that he/she/they was/were your cousin. Yes, the cousin that complained about the slow updates, the one you absentmindedly said "You don't know programming at all" in rage to, and shortly after realized you didn't too. Soon you started to learn programming, and so did he/she/they. This is probably the craziest thing I've ever speculated. :P

**Comment by viperxlink** [comment]
# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]

**Comment by viperxlink** [comment]
# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]

**Comment by viperxlink** [comment]
# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]

**Comment by viperxlink** [comment]
# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]

**Comment by viperxlink** [comment]
# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]
